### PR TITLE
Issue329 issue handling workflow to docs

### PR DESCRIPTION
**Pull request by jonbergh**
Review of issues/hotfix handling in `conventions.rst` to be more clear and consistent.

### CODE REVIEW

**Comment by mortenwh** [comment]
Can you solve the conflicts? I guess you'll need to merge with develop first...

**Comment by jonbergh** [comment]
@mortenwh can you help with this fail, see end of log file in Travis CI check!

**Comment by mortenwh** [comment]
This is a bit strange.. You have only worked on the docs, haven't you?

**Comment by mortenwh** [comment]
Apparently, @akorosov has solved this issue in another branch. This will soon be merged with master and develop.

**Comment by jonbergh** [comment]
We close this pull request for now and restart from updated code!

**Pull request closed without merging**
